name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$NVM_DIR/versions/node/$(nvm version)/bin:$PATH"
            cd ghprojects/WMS-Doxa-front/
            git stash push -m "CI/CD stash"
            git pull origin main --rebase
            git stash pop || true
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2
            npm install
            pm2 restart doxa_front
